# Generated by Django 4.2.23 on 2025-07-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
