# Generated by Django 4.2.23 on 2025-07-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
