# Generated by Django 4.2.23 on 2025-07-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
